// examples/astro/src/components/Example.tsx
import type { JSX } from 'solid-js';
import {
  createResource, createSignal, onMount, Show, Suspense,
} from 'solid-js';

async function sleep<T>(value: T, ms: number): Promise<T> {
  return new Promise<T>((res) => {
    setTimeout(res, ms, value);
  });
}

function ClientOnly(props: { children: JSX.Element }): JSX.Element {
  const [flag, setFlag] = createSignal(false);

  onMount(() => {
    setFlag(true);
  });

  return (
    <Show when={flag()}>
      {props.children}
    </Show>
  );
}

function Inner(): JSX.Element {
  const [state, setState] = createSignal(0);

  const prefix = 'Server Count';

  async function serverCount(value: number) {
    'use server';

    console.log('Received', value);
    const immediate = `${prefix}: ${value}`;
    return {
      immediate,
      delayed: sleep(immediate, 5000),
    };
  }

  const [data] = createResource(state, async (value) => serverCount(value));

  function increment(): void {
    setState((c) => c + 1);
  }

  return (
    <>
      <button type="button" onClick={increment}>
        {`Client Count: ${state()}`}
      </button>
      <div>
        <Suspense fallback={<h1>Loading</h1>}>
          <h1>{data()?.immediate}</h1>
        </Suspense>
      </div>
    </>
  );
}

export default function Example(): JSX.Element {
  return (
    <ClientOnly>
      <Inner />
    </ClientOnly>
  );
}

// examples/sveltekit/src/components/Example.svelte
<script>
  const prefix = 'Server Count';

  async function serverCount(value) {
    'use server';

    console.log('Received', value);
    const immediate = `${prefix}: ${value}`;
    return {
      immediate,
      delayed: new Promise((res) => {
        setTimeout(res, 1000, immediate);
      }),
    };
  }

  let state = 0;

  $: data = serverCount(state);

  function increment() {
    state += 1;
  }
</script>
<button on:click={increment}>
  {`Client Count: ${state}`}
</button>
<div>
  {#await data}
    <h1>Loading</h1>
  {:then value}
    <h1>{value.immediate}</h1>
    {#await value.delayed}
      <h1>Loading</h1>
    {:then delayed}
      <h1>Delayed: {delayed}</h1>
    {/await}
  {/await}
</div>
